CONNECT 'jdbc:derby://localhost:1527/Team19DB;create=true';
CREATE TABLE "APP"."USERS" (
                               "NOME" VARCHAR(40),
                               "COGNOME" VARCHAR(40),
                               "DATADINASCITA" DATE,
                               "EMAIL" VARCHAR(50),
                               "TELEFONO" VARCHAR(14),
                               "TIPOLOGIA" VARCHAR(20),
                               "USERNAME" VARCHAR(50) NOT NULL,
                               "PASSWORD" VARCHAR(50)
);

INSERT INTO "APP"."USERS" ("NOME", "COGNOME", "DATADINASCITA", "EMAIL", "TELEFONO", "TIPOLOGIA", "USERNAME", "PASSWORD")
VALUES ('Admin', 'User', '1980-01-01', 'admin@example.com', '1234567890', 'amministratore', 'admin', 'admin');

INSERT INTO "APP"."USERS" ("NOME", "COGNOME", "DATADINASCITA", "EMAIL", "TELEFONO", "TIPOLOGIA", "USERNAME", "PASSWORD")
VALUES ('Simone', 'Rossi', '1990-05-15', 'simpatizzante@example.com', '0987654321', 'simpatizzante', 'simpatico', 'simpatico');

INSERT INTO "APP"."USERS" ("NOME", "COGNOME", "DATADINASCITA", "EMAIL", "TELEFONO", "TIPOLOGIA", "USERNAME", "PASSWORD")
VALUES ('Luca', 'Bianchi', '2000-03-10', 'aderente@example.com', '1122334455', 'aderente', 'aderente', 'aderente');


ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL0000000081-24fa0130-0188-b583-a30a-00000f7980d0" PRIMARY KEY ("USERNAME");

CREATE TABLE "APP"."DONAZIONI" (
                                   "NUMERODONAZIONE" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
                                   "IMPORTO" DECIMAL(7,2) NOT NULL,
                                   "VALUTA" VARCHAR(10) DEFAULT 'Euro',
                                   "DATADONAZIONE" DATE DEFAULT CURRENT_DATE
);

ALTER TABLE "APP"."DONAZIONI" ADD CONSTRAINT "SQL0000000082-0f134137-0188-b583-a30a-00000f7980d0" PRIMARY KEY ("NUMERODONAZIONE");
ALTER TABLE "APP"."DONAZIONI" ADD CONSTRAINT "SQL0000000083-e7610138-0188-b583-a30a-00000f7980d0" CHECK (Importo > 0);
INSERT INTO "APP"."DONAZIONI" ("IMPORTO", "VALUTA", "DATADONAZIONE")
VALUES (100.00, 'Euro', '2025-01-15');

INSERT INTO "APP"."DONAZIONI" ("IMPORTO", "VALUTA", "DATADONAZIONE")
VALUES (50.00, 'Euro', '2025-02-10');

INSERT INTO "APP"."DONAZIONI" ("IMPORTO", "VALUTA", "DATADONAZIONE")
VALUES (200.00, 'Euro', '2025-03-01');

INSERT INTO "APP"."DONAZIONI" ("IMPORTO", "VALUTA", "DATADONAZIONE")
VALUES (75.00, 'Euro', '2025-03-10');

INSERT INTO "APP"."DONAZIONI" ("IMPORTO", "VALUTA", "DATADONAZIONE")
VALUES (120.00, 'Euro', '2025-03-15');

CREATE TABLE "APP"."CONTATORI" (
                                   "PAGINA" VARCHAR(30) NOT NULL,
                                   "VALORE" INTEGER NOT NULL
);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Aderente', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Amministratore', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Attivita', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Aisha', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Team4World', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Abc4Future', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('ChiSiamo', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('ConfermaSignIn', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Contatti', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('ProfiloEliminato', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Home', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Generale', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('InvioConfermato', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Login', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Logout', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('SignIn', 0);

INSERT INTO "APP"."CONTATORI" ("PAGINA", "VALORE")
VALUES ('Simpatizzante', 0);

ALTER TABLE "APP"."CONTATORI" ADD CONSTRAINT "SQL0000000086-3f9e4152-0188-b583-a30a-00000f7980d0" PRIMARY KEY ("PAGINA");
ALTER TABLE "APP"."CONTATORI" ADD CONSTRAINT "SQL0000000087-d7f2c153-0188-b583-a30a-00000f7980d0" CHECK (Valore >= 0);

CREATE TABLE "APP"."FRASIISPIRANTI" (
                                        "NUMEROFRASE" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
                                        "FRASE" VARCHAR(300) NOT NULL
);

ALTER TABLE "APP"."FRASIISPIRANTI" ADD CONSTRAINT "SQL0000000084-d2c8c143-0188-b583-a30a-00000f7980d0" PRIMARY KEY ("NUMEROFRASE");

CREATE TABLE "APP"."ISCRIZIONI" (
                                    "USERNAME" VARCHAR(50) NOT NULL,
                                    "ATTIVITA" INTEGER NOT NULL
);

ALTER TABLE "APP"."ISCRIZIONI" ADD CONSTRAINT "SQL0000000085-5555c14b-0188-b583-a30a-00000f7980d0" PRIMARY KEY ("USERNAME", "ATTIVITA");
